
# zsh-atuosuggestions keybindings

bindkey '^ ' autosuggest-accept

## Aliases {{{

alias ll="ls -all"
alias dot="cd ~/.dotfiles && ll"
alias opt="cd /opt"
alias prj="cd ~/projects"
mdd() { mkdir -p $1 && cd $1 }

## }}}

export TERM=xterm-256color

export EDITOR="vim"

source ~/cntlm_proxy
